# Numpy
```
    pip install numpy
```
    Used for Mathematical Calculations
    for data maniulations numpy 
    library for array operations ka liya
    Numpy Array Creation
    Shape
    indexing
    data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
    more creation methods: arange, linspace, ones, zeros, eye, diag
    random numbers: Numpy Random Module
        rand: Random values in given shape
        randn: Return samples from the Standard normal distribution
        randint: Return random integer from low(inclusive) to high(exclusive)
        random: Return random floats in [0.0,1.0)
        choice: Generates a random sample from given 1D array
        Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
        reshape: -1 for unknown
    slicing and assignment
    copy and view: share_memory
    operators(Element wise operations)
    and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
    shape mismatch
    fancy indexing also know as filter
    search: where uses fancy indexing
    Basic reductions: sum, min, max, any, all,argmax, argmin
    Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
    iteration: nditer, ndenumerate
    Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
    split: array_split, hsplit
    sort: np.sort
    Broadcasting
    Input from Text File
    Questions

In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)

2.1.3


In [3]:
l1=[1,2,3,4]
l2=[[1,2],[3,4],[5,6]]
l3=[[[10,20],[30,40]],[[1,2],[3,4]]]

In [4]:
 n1=np.array(l1)
 n2=np.array(l2)
 n3=np.array(l3)

In [5]:
type(n1)

numpy.ndarray

In [6]:
n1.shape

(4,)

In [7]:
n2.shape

(3, 2)

In [8]:
n3.shape

(2, 2, 2)

In [9]:
print(l1[2],n1[2])

3 3


In [12]:
# print(l2[1][1],n2[1][1])
print(l2[1][1],n2[1,1])

4 4


In [13]:
print(l3[0][1][0],n3[0,1,0])

30 30


In [14]:
l2[1]

[3, 4]

In [15]:
n2[1]

array([3, 4])

In [18]:
narr = np.arange(1,11)

In [19]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
np.ones(shape=(3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
np.zeros(shape=(3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
np.eye(4,4) #gives identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
narr = np.arange(1,101)

In [33]:
narr.reshape((10,10))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [35]:
np.random.randn(3,2,2)

array([[[ 0.65883611,  1.53973289],
        [-0.59843243, -1.20766176]],

       [[-0.23893778, -0.51344031],
        [-1.71960453,  0.84841897]],

       [[-1.30438333, -0.92184428],
        [-0.10478422, -0.33756765]]])

In [37]:
np.random.randint(1,101,size=(5,2))

array([[76, 56],
       [10, 65],
       [30, 21],
       [17, 99],
       [71, 97]])

In [38]:
np.random.random(size=(5,2))

array([[0.15006146, 0.31936307],
       [0.29135889, 0.11582659],
       [0.70689073, 0.49060434],
       [0.39728588, 0.81602579],
       [0.78944735, 0.48479701]])

In [41]:
np.random.choice(np.arange(1,101,2),size=(5,3),replace = False)

array([[17, 69, 49],
       [ 5, 61, 43],
       [53, 41, 85],
       [39, 81, 75],
       [ 9, 55, 47]])

In [44]:
narr=np.arange(1,101)
np.random.shuffle(narr)

In [45]:
narr

array([ 66,  63,  22,  77,   2,  17,   9,  11,  91,  35,  14,  28,  89,
        70,  12,  64,  68,  67,  94,  84,  49,  15,  72,  53,  16,  58,
        76,  23,  41,  65,  57,  30,  88,  21,  86,  62,  55,   1,   5,
        81,  79,  82,  93,  43,  34,  38,   8,  83,  92,   3,  59,  24,
        99,  97,  26,  75,  33, 100,  61,  29,  96,  95,  10,  13,  85,
        87,  60,  36,  78,  32,  56,  42,  73,  31,   6,  27,  48,  47,
        20,  40,  18,  71,  44,  98,  54,  52,  19,   4,  50,  25,  46,
        74,  39,  69,  80,  90,  51,  45,   7,  37])

In [47]:
narr = narr.reshape((-1,))

In [51]:
narr = np.arange(1,101).reshape(10,10)

In [52]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [66]:
narr[3:7,4:8] =np.eye(4)

In [67]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [68]:
brr = narr[3:7,4:8]

In [71]:
brr[1:3,1:3] = np.ones(shape=(2,2))

In [72]:
brr

array([[1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [73]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   1,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   1,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [80]:
n1=np.array([1,2,3,4,5,])
n2=np.array([10,20,30,40,50])

In [81]:
n1+10

array([11, 12, 13, 14, 15])

In [82]:
n1+n2

array([11, 22, 33, 44, 55])

In [2]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([10,20,30,40,50])

In [3]:
n1+3

array([4, 5, 6, 7, 8])

In [4]:
n1-3

array([-2, -1,  0,  1,  2])

In [5]:
n1/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [6]:
n1//3

array([0, 0, 1, 1, 1])

In [7]:
n1>3

array([False, False, False,  True,  True])

In [8]:
n1=np.array([[1,2,3],[4,5,6]])
n2=np.array([[10,20,30],[40,50,60]])

In [9]:
n1+n2

array([[11, 22, 33],
       [44, 55, 66]])

In [10]:
n1-n2

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [11]:
n1-n1

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
m1*n2

NameError: name 'm1' is not defined

In [13]:
n1*n2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [14]:
n1/n2

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [15]:
n1 <n2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [16]:
n1*10+n2

array([[ 20,  40,  60],
       [ 80, 100, 120]])

In [18]:
n1 = np.arange(1,21)

In [19]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
np.random.shuffle(n1)

In [21]:
n1

array([ 2, 16,  3, 15, 10, 13,  7, 20, 14,  5,  9,  4, 12,  1, 11, 18, 17,
        8,  6, 19])

In [23]:
n1[[1,4,10]]

array([16, 10,  9])

In [47]:
n1 = np.arange(1,101).reshape((10,10))

In [48]:
n1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [49]:
n1[[1,4,8],[0,3,7]]

array([11, 44, 88])

In [51]:
n1[[True,False,False,True,False,False,False,True,False,True]]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [54]:
n1[n1>10]

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [57]:
n3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
n3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
n3.sum()
np.sum(n3)

np.int64(45)

In [75]:
n4=np.array([[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]])

In [76]:
n4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [77]:
n4.sum(axis=0)

array([[11, 22],
       [33, 44],
       [55, 66]])

In [78]:
n4.sum(axis=1)

array([[  9,  12],
       [ 90, 120]])

In [79]:
n4.sum(axis=2)

array([[  3,   7,  11],
       [ 30,  70, 110]])

In [84]:
n3.sum(axis=1)

array([ 6, 15, 24])

In [86]:
for t in np.ndenumerate(n1):
    print(t)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((0, 3), np.int64(4))
((0, 4), np.int64(5))
((0, 5), np.int64(6))
((0, 6), np.int64(7))
((0, 7), np.int64(8))
((0, 8), np.int64(9))
((0, 9), np.int64(10))
((1, 0), np.int64(11))
((1, 1), np.int64(12))
((1, 2), np.int64(13))
((1, 3), np.int64(14))
((1, 4), np.int64(15))
((1, 5), np.int64(16))
((1, 6), np.int64(17))
((1, 7), np.int64(18))
((1, 8), np.int64(19))
((1, 9), np.int64(20))
((2, 0), np.int64(21))
((2, 1), np.int64(22))
((2, 2), np.int64(23))
((2, 3), np.int64(24))
((2, 4), np.int64(25))
((2, 5), np.int64(26))
((2, 6), np.int64(27))
((2, 7), np.int64(28))
((2, 8), np.int64(29))
((2, 9), np.int64(30))
((3, 0), np.int64(31))
((3, 1), np.int64(32))
((3, 2), np.int64(33))
((3, 3), np.int64(34))
((3, 4), np.int64(35))
((3, 5), np.int64(36))
((3, 6), np.int64(37))
((3, 7), np.int64(38))
((3, 8), np.int64(39))
((3, 9), np.int64(40))
((4, 0), np.int64(41))
((4, 1), np.int64(42))
((4, 2), np.int64(43))
((4, 3), np.int64(44

In [90]:
n8 = np.arange(1,13).reshape(4,3)

In [91]:
n8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
np.array([10,20,30])+n8

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [101]:
pop = np.loadtxt("population.txt")
pop.max(axis=0)

array([ 1920., 77400., 59400., 48300.])

In [105]:
pop[:,0][pop.argmax(axis=0)][1:]

array([1903., 1904., 1900.])